CREATE TABLE IF NOT EXISTS travel_destinations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  country VARCHAR(80) NOT NULL,
  category VARCHAR(60) NOT NULL,
  description TEXT NOT NULL,
  rating DECIMAL(2, 1) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
